version: '3'
services:
    app:
        build: .
        expose:
            - "8180"
            - "80"
        restart: unless-stopped
        ports:
            - "8180:8180"
            - "3000:80"
        volumes:
            - ./src:/srv/app/REPLACE ME/src
            - ./public:/srv/app/REPLACE ME/public
        command: [ "node", "server.js" ]
